### ISSUE TITLE
Changing a User status from Inactive to Locked doesn't enable the save button

### ISSUE THREAD

**Issue by stroomdev10** [gchq/stroom-auth#111]
Possibly because the password isn't long enough?

Password length is irrelevant here

**Comment by stroomdev10** [comment]
Possibly because the password isn't long enough?

**Comment by jc064522** [comment]
It does enable the save button but you have to click away for that to happen. There's similar behaviour on other forms. I think this is coming from the otherwise marvellous Formik form library. It's annoying so I'll investigate.

**Comment by jc064522** [comment]
The submit button depends on the form being 'touched'. Formik doesn't consider a field 'touched' until there's been a blur event. I don't think that's ideal in some cases, especially this one. I'd rather see it 'touched'  on change. I've added 'touch on change' for this specific field, which means you don't have to click away from the field for the change to register. This should really be the default for drop-downs. 

I'll certainly be putting this on other fields.
